/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "hbabranmwzppeuyczvlv"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhiYWJyYW5td3pwcGV1eWN6dmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MTQ1MzYsImV4cCI6MjA3Njk5MDUzNn0.EU0D0MXmlPTAws9bHoFuPF--QcA4IbWI1FDZC9vjmGY"